### ISSUE TITLE
Develop Pipeline from raw scSeq data to Annotation

### ISSUE THREAD

**Issue by tim-schubert** [biocypher/sc2cl#12]

**Comment by tim-schubert** [comment]
Seurat works well for handling data. The output is a .csv file per cell with the gene expression listed from highest to lowest count.
This part could be augmented by integrating other packages for handling single cell data in the future.

**Comment by slobentanzer** [comment]
Hi @tim-schubert, where is the code for this?

**Comment by tim-schubert** [comment]
Hi @slobentanzer, @JonasJuergensen will push it alongside the rest of the code.

**Comment by slobentanzer** [comment]
Alright. Bear in mind that I will still need to go over it to grade it, and Sandy wants the form returned tomorrow. The official deadline for the code was yesterday.

**Comment by tim-schubert** [comment]
Thanks, I will remind him.
