### ISSUE TITLE
Ontology mapping

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/sc2cl#3]
The task is to map free-text terms to CL, using CCB (Harvard) ontology mapper tool, tool from last WFT iteration, API calls, etc.

**Comment by simonmoedinger** [comment]
task 2: Cell Ontology mapping.

1. Compare literature for strategies of annotation to ontology mapping and discuss the problem

-  [ccb](https://github.com/ccb-hms/ontology-mapper) 
-  [Last years project](https://github.com/cieldeville/ontology-mapping)

2. Ideas how to compare these methods? Are there more mehtods out? What could be a possible benchmark study? 
2.1. Select one or multiple methods and build a ontology mapping pipeline for free text cell annotations from the heart. 

- Input : cell annotations [like](https://docs.google.com/spreadsheets/d/1dlSbsRTn8Od9YOAbU-WzSlt8a_LR7ZZz5LDccmCdX-w/edit?usp=sharing)
- Output: [CL annotations](https://www.ebi.ac.uk/ols/ontologies/cl)
