### ISSUE TITLE
Use cell markers (CellMarker2) to determine cell types

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/sc2cl#4]
Calling cell types, even previously unknown ones, using molecular markers.

**Comment by simonmoedinger** [comment]
task 3: Cell annotation with cell ontology

1. Use marker resources, e.g. CellMarker2 Db, Human Protein Atlas to build a pipeline to annotate single cell data with cell ontology ([here](https://www.ebi.ac.uk/ols/ontologies/cl))

2.  To develop the pipeline you can use toy data, e.g. the infamous pbmc data from 10x (example how to download and process with [Seurat](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html).) To handle single cell data in R, SingleCellExperiment or Seurat are standard packages; in python it is scanpy. 

3.  If the pipeline is built, try more challenging data sets from the heart: 

- [ reichart et al.](https://cellxgene.cziscience.com/collections/e75342a8-0f3b-4ec5-8ee1-245a23e0f7cb/private)
- [kuppe et al.](https://cellxgene.cziscience.com/collections/8191c283-0816-424b-9b61-c3e1d6258a77)

4. Compare strategies to existing tools. e.g. 

- [bernstein et al.](https://www.sciencedirect.com/science/article/pii/S258900422031110X)
- [wang et al.](https://www.nature.com/articles/s41467-021-25725-x)

**Comment by JanLanzer** [comment]
From discussions on 13.04
improvement for marker selection:
brainstorm about expression patterns you would expect of good cell type marker. Clustering resolution can be somewhat arbitrary, how does this effect cluster Cell ontology assignment? see https://www.nature.com/articles/s41467-021-21453-4 for example of identifiying stable cluster markers. Further, use HPA and or cellmarker2 to score marker themselves for celltype or tissue specificity (make this an option for the user to choose whether this is desired)
improvement for CL suggestion:
the overlap does not take into account the probability of finding an  overlap by chance. Use hypergeometric test to assess significance of marker overlap. When weights are available these can be considered by more sophisticated models (see decoupleR package for collection of methods)

**Comment by JonasJuergensen** [comment]
Marker2Cell works for annotating single cells based on their RNA expression profile.
