### ISSUE TITLE
Test ccb tool

### ISSUE THREAD

**Issue by simonmoedinger** [biocypher/sc2cl#6]

**Comment by simonmoedinger** [comment]
Repo

**Comment by RM7** [comment]
I run the ccb tool with the parameter save_graphs=true and have got a mapping.txt-term-graphs.json file. 
We will try to visualise it.

**Comment by RM7** [comment]
We tried to visualise the created graph online. It looks like that the gaph is a visualisation of the cell ontology and not of the mapping. So we will try to visualise the mapping by ourselfs.
